elasticsearch:
  a:
    b: a
  indexSettings:
    store:
      name: stores
      type: store
      mappingFile: stores_mapping.json

spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS : true
